### ISSUE TITLE
[Strapi 4] Cannot update a User collection item

### ISSUE THREAD

**Issue by cossssmin** [Stun3R/strapi-sdk-js#128]
### Describe the bug

When using `strapi-sdk-js@2.1.5` with Strapi 4, I am unable to update a User collection with `strapi.update()`.

### Steps to reproduce the behavior

I have a `User` collection that, among other fields, has these:

![image](https://user-images.githubusercontent.com/1656595/153474388-14327c62-ec61-4160-8587-db45e4f70e40.png)

I am using the SDK in Nuxt 2, so I followed your [instructions](https://strapi-sdk-js.netlify.app/going-further/integrations#nuxt-2) to integrate it. So far auth methods working well.

On a settings page that I have, I'm doing this:

```js
async saveFirstName() {
  await this.$strapi.update('users', this.user.id, {
    firstName: this.user.firstName,
  })
},
```

That sends this payload:

![image](https://user-images.githubusercontent.com/1656595/153474967-24111978-9642-4c69-ab86-37e7be66c735.png)

However, the field isn't updated and the returned object also contains it as `null`:

![image](https://user-images.githubusercontent.com/1656595/153475533-f8505fdf-c580-4620-8b41-b82fd14b3e1f.png)

However, if I manually `PUT` to the `/api/users/19`, it works just fine:

![image](https://user-images.githubusercontent.com/1656595/153478165-242b711f-e8a4-41a6-bc03-07ecad21b00f.png)

Can it be because of the nested `data` object that is sent when updating a resource?

![image](https://user-images.githubusercontent.com/1656595/153474967-24111978-9642-4c69-ab86-37e7be66c735.png)

**Comment by Stun3R** [comment]
Hi @cossssmin 

Thanks for this issue! Indeed **Users & Permissions plugin** has not be updated in order to follow `Strapi v4 CRUD format`, so the nested `data` object doesn't work here. (See the U&P update method: [here](https://github.com/strapi/strapi/blob/master/packages/plugins/users-permissions/server/controllers/user.js#L91) 

In order to update the user correctly you can use `strapi.request` as below:
```js
const user = await this.$strapi.request('put', `/users/${this.user.id}`, {
   data: {
      firstName: this.user.firstName,
  },
})
```

Sorry again for this issue but it's something regarding **Users & Permissions plugin** ☹️

**Comment by cossssmin** [comment]
Thanks for the quick reply and the alternative solution, works great 👍
