### ISSUE TITLE
Why the older version has been removed ?

### ISSUE THREAD

**Issue by jvgaeta** [Stun3R/strapi-sdk-js#30]
We've been using this package, but it's suddenly not on npm. Is this intentional?

https://www.npmjs.com/package/strapi-sdk-js now yields a 404.

**Comment by Stun3R** [comment]
Hi @jvgaeta 👋🏻

This is intentional. I'm working on a total rework.

I'll republish it soon and will be fully available next week ☺️

Sorry for the miscommunication about it but the older package was unfinished and I preferred to rework it totally in order to implements a complete one ❤️

**Comment by Stun3R** [comment]
> We've been using this package, but it's suddenly not on npm. Is this intentional?
> 
> https://www.npmjs.com/package/strapi-sdk-js now yields a 404.

@jvgaeta & @etankhanal

It should be fixed: https://www.npmjs.com/package/strapi-sdk-js

For more informations see this discussion: https://github.com/Stun3R/strapi-sdk-js/discussions/32

Sorry again for the inconvenience. This package will now be maintain at 100% & this kind of issue will not happen again 🙏🏻

**Comment by jvgaeta** [comment]
Thank you! :)

**Comment by etankhanal** [comment]
Much appreciated!!

**Comment by Stun3R** [comment]
As @lhillebrandt discovered today, the package encountered a problem... The `dist` folder wasn't include inside the npm package for mysterious reason.

I'll republish a new version tomorrow since I can't republish within 24 hours 🙏🏻
This is the beginning of this package that's why there is some "bugs". Normally It should be stable from now 😎

**Comment by Stun3R** [comment]
It's fixed and I just released it: https://www.npmjs.com/package/strapi-sdk-js
